// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type SegmentsResource struct{ c *Client }

// Create — POST /segments
func (r *SegmentsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/segments"+encodeQuery(params), body)
}

// Delete — DELETE /segments/:id
func (r *SegmentsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", fmt.Sprintf("/segments/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// Get — GET /segments/:id
func (r *SegmentsResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/segments/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /segments
func (r *SegmentsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/segments"+encodeQuery(params), nil)
}

// Members — GET /v1/segments/:id/members
func (r *SegmentsResource) Members(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/v1/segments/%s/members", url.PathEscape(id))+encodeQuery(params), nil)
}

// Preview — POST /segments/:id/preview
func (r *SegmentsResource) Preview(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/segments/%s/preview", url.PathEscape(id))+encodeQuery(params), body)
}

// Refresh — POST /segments/:id/refresh
func (r *SegmentsResource) Refresh(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/segments/%s/refresh", url.PathEscape(id))+encodeQuery(params), nil)
}

// Update — PATCH /segments/:id
func (r *SegmentsResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/segments/%s", url.PathEscape(id))+encodeQuery(params), body)
}
