// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type SettingsResource struct{ c *Client }

// Audit — GET /settings/audit
func (r *SettingsResource) Audit(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/audit"+encodeQuery(params), nil)
}

// CreateDedicatedIps — POST /settings/dedicated-ips
func (r *SettingsResource) CreateDedicatedIps(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/dedicated-ips"+encodeQuery(params), nil)
}

// CreateIpPools — POST /settings/ip-pools
func (r *SettingsResource) CreateIpPools(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/ip-pools"+encodeQuery(params), body)
}

// CreateSignatures — POST /settings/signatures
func (r *SettingsResource) CreateSignatures(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/signatures"+encodeQuery(params), body)
}

// CreateSmtpPools — POST /settings/smtp-pools
func (r *SettingsResource) CreateSmtpPools(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/smtp-pools"+encodeQuery(params), body)
}

// CreateUnsubscribePage — POST /settings/unsubscribe-page
func (r *SettingsResource) CreateUnsubscribePage(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/unsubscribe-page"+encodeQuery(params), body)
}

// CreateWhitelabel — POST /settings/whitelabel
func (r *SettingsResource) CreateWhitelabel(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/settings/whitelabel"+encodeQuery(params), body)
}

// DeleteIpPools — DELETE /settings/ip-pools
func (r *SettingsResource) DeleteIpPools(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/settings/ip-pools"+encodeQuery(query), nil)
}

// DeleteSignatures — DELETE /settings/signatures
func (r *SettingsResource) DeleteSignatures(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/settings/signatures"+encodeQuery(query), nil)
}

// DeleteSmtpPools — DELETE /settings/smtp-pools
func (r *SettingsResource) DeleteSmtpPools(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/settings/smtp-pools"+encodeQuery(query), nil)
}

// ListDedicatedIps — GET /settings/dedicated-ips
func (r *SettingsResource) ListDedicatedIps(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/dedicated-ips"+encodeQuery(params), nil)
}

// ListIpPools — GET /settings/ip-pools
func (r *SettingsResource) ListIpPools(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/ip-pools"+encodeQuery(params), nil)
}

// ListSignatures — GET /settings/signatures
func (r *SettingsResource) ListSignatures(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/signatures"+encodeQuery(params), nil)
}

// ListSmtpPools — GET /settings/smtp-pools
func (r *SettingsResource) ListSmtpPools(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/smtp-pools"+encodeQuery(params), nil)
}

// ListUnsubscribePage — GET /settings/unsubscribe-page
func (r *SettingsResource) ListUnsubscribePage(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/unsubscribe-page"+encodeQuery(params), nil)
}

// ListWhitelabel — GET /settings/whitelabel
func (r *SettingsResource) ListWhitelabel(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/settings/whitelabel"+encodeQuery(params), nil)
}

// UpdateSignatures — PUT /settings/signatures
func (r *SettingsResource) UpdateSignatures(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PUT", "/settings/signatures"+encodeQuery(params), body)
}
