// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type LabelsResource struct{ c *Client }

// Create — POST /labels
func (r *LabelsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/labels"+encodeQuery(params), body)
}

// Delete — DELETE /labels
func (r *LabelsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/labels"+encodeQuery(query), nil)
}

// List — GET /labels
func (r *LabelsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/labels"+encodeQuery(params), nil)
}
