// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type NotificationsResource struct{ c *Client }

// List — GET /notifications
func (r *NotificationsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/notifications"+encodeQuery(params), nil)
}

// Update — PATCH /notifications
func (r *NotificationsResource) Update(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", "/notifications"+encodeQuery(params), body)
}
