// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type DedicatedIpsResource struct{ c *Client }

// Create — POST /v1/dedicated-ips
func (r *DedicatedIpsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/dedicated-ips"+encodeQuery(params), body)
}

// Get — GET /v1/dedicated-ips/:id
func (r *DedicatedIpsResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/v1/dedicated-ips/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /v1/dedicated-ips
func (r *DedicatedIpsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/dedicated-ips"+encodeQuery(params), nil)
}

// Update — PATCH /v1/dedicated-ips/:id
func (r *DedicatedIpsResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/v1/dedicated-ips/%s", url.PathEscape(id))+encodeQuery(params), body)
}
