// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type WorkspacesResource struct{ c *Client }

// TeamMembers — GET /v1/team-members
func (r *WorkspacesResource) TeamMembers(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/team-members"+encodeQuery(params), nil)
}
