// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type CampaignsResource struct{ c *Client }

// Create — POST /v1/campaigns
func (r *CampaignsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/campaigns"+encodeQuery(params), body)
}

// Delete — DELETE /v1/campaigns/:id
func (r *CampaignsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", fmt.Sprintf("/v1/campaigns/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// Get — GET /v1/campaigns/:id
func (r *CampaignsResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/v1/campaigns/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /v1/campaigns
func (r *CampaignsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/campaigns"+encodeQuery(params), nil)
}

// Send — POST /v1/campaigns/:id/send
func (r *CampaignsResource) Send(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/v1/campaigns/%s/send", url.PathEscape(id))+encodeQuery(params), nil)
}

// Update — PATCH /v1/campaigns/:id
func (r *CampaignsResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/v1/campaigns/%s", url.PathEscape(id))+encodeQuery(params), body)
}
