// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type MonetizationResource struct{ c *Client }

// Stats — GET /v1/monetization/stats
func (r *MonetizationResource) Stats(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/monetization/stats"+encodeQuery(params), nil)
}

// Tip — POST /v1/monetization/tip
func (r *MonetizationResource) Tip(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/monetization/tip"+encodeQuery(params), body)
}
