// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type DeliverabilityResource struct{ c *Client }

// CreateAudit — POST /deliverability/audit
func (r *DeliverabilityResource) CreateAudit(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/deliverability/audit"+encodeQuery(params), nil)
}

// History — GET /deliverability/history
func (r *DeliverabilityResource) History(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/deliverability/history"+encodeQuery(params), nil)
}

// ListAudit — GET /v1/deliverability/audit
func (r *DeliverabilityResource) ListAudit(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/deliverability/audit"+encodeQuery(params), nil)
}

// Playbooks — GET /deliverability/playbooks
func (r *DeliverabilityResource) Playbooks(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/deliverability/playbooks"+encodeQuery(params), nil)
}

// Score — GET /v1/deliverability/score
func (r *DeliverabilityResource) Score(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/deliverability/score"+encodeQuery(params), nil)
}

// SendTime — GET /deliverability/send-time
func (r *DeliverabilityResource) SendTime(ctx context.Context, campaignId string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("campaignId") == "" {
		query.Set("campaignId", campaignId)
	}
	return r.c.Do(ctx, "GET", "/deliverability/send-time"+encodeQuery(query), nil)
}
