// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type DmarcResource struct{ c *Client }

// Check — GET /v1/dmarc/check
func (r *DmarcResource) Check(ctx context.Context, domain string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("domain") == "" {
		query.Set("domain", domain)
	}
	return r.c.Do(ctx, "GET", "/v1/dmarc/check"+encodeQuery(query), nil)
}

// CreateDomains — POST /v1/dmarc/domains
func (r *DmarcResource) CreateDomains(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/dmarc/domains"+encodeQuery(params), body)
}

// DeleteDomains — DELETE /v1/dmarc/domains
func (r *DmarcResource) DeleteDomains(ctx context.Context, domainId string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("domain_id") == "" {
		query.Set("domain_id", domainId)
	}
	return r.c.Do(ctx, "DELETE", "/v1/dmarc/domains"+encodeQuery(query), nil)
}

// ListDomains — GET /v1/dmarc/domains
func (r *DmarcResource) ListDomains(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/dmarc/domains"+encodeQuery(params), nil)
}
