// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type ComplianceResource struct{ c *Client }

// CreateConfirmSubscription — POST /public/subscriptions/confirm — public double opt-in confirmation (no API key required)
func (r *ComplianceResource) CreateConfirmSubscription(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/public/subscriptions/confirm"+encodeQuery(params), body)
}

// CreateUnsubscribe — POST /unsubscribe — public one-click unsubscribe (no API key required)
func (r *ComplianceResource) CreateUnsubscribe(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/unsubscribe"+encodeQuery(params), body)
}

// ListConfirmSubscription — GET /public/subscriptions/confirm — public double opt-in confirmation (no API key required)
func (r *ComplianceResource) ListConfirmSubscription(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/public/subscriptions/confirm"+encodeQuery(params), nil)
}

// ListUnsubscribe — GET /unsubscribe — public one-click unsubscribe (no API key required)
func (r *ComplianceResource) ListUnsubscribe(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/unsubscribe"+encodeQuery(params), nil)
}
