// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

// Resources lists every generated resource attached to a Client.
type Resources struct {
	AbTests *AbTestsResource
	Ai *AiResource
	Analytics *AnalyticsResource
	Automations *AutomationsResource
	Billing *BillingResource
	Campaigns *CampaignsResource
	Compliance *ComplianceResource
	Contacts *ContactsResource
	DedicatedIps *DedicatedIpsResource
	Deliverability *DeliverabilityResource
	Dmarc *DmarcResource
	Domains *DomainsResource
	Drafts *DraftsResource
	Email *EmailResource
	EmailAccounts *EmailAccountsResource
	Forms *FormsResource
	Inbound *InboundResource
	Inbox *InboxResource
	Integrations *IntegrationsResource
	Keys *KeysResource
	Labels *LabelsResource
	LandingPages *LandingPagesResource
	Marketplace *MarketplaceResource
	Monetization *MonetizationResource
	Notifications *NotificationsResource
	Preferences *PreferencesResource
	Referrals *ReferralsResource
	Sandbox *SandboxResource
	Segments *SegmentsResource
	Settings *SettingsResource
	Templates *TemplatesResource
	Track *TrackResource
	Validate *ValidateResource
	Wallet *WalletResource
	Warmup *WarmupResource
	Workspaces *WorkspacesResource
}

// attachResources wires each generated resource to its client.
func (c *Client) attachResources() {
	c.AbTests = &AbTestsResource{c: c}
	c.Ai = &AiResource{c: c}
	c.Analytics = &AnalyticsResource{c: c}
	c.Automations = &AutomationsResource{c: c}
	c.Billing = &BillingResource{c: c}
	c.Campaigns = &CampaignsResource{c: c}
	c.Compliance = &ComplianceResource{c: c}
	c.Contacts = &ContactsResource{c: c}
	c.DedicatedIps = &DedicatedIpsResource{c: c}
	c.Deliverability = &DeliverabilityResource{c: c}
	c.Dmarc = &DmarcResource{c: c}
	c.Domains = &DomainsResource{c: c}
	c.Drafts = &DraftsResource{c: c}
	c.Email = &EmailResource{c: c}
	c.EmailAccounts = &EmailAccountsResource{c: c}
	c.Forms = &FormsResource{c: c}
	c.Inbound = &InboundResource{c: c}
	c.Inbox = &InboxResource{c: c}
	c.Integrations = &IntegrationsResource{c: c}
	c.Keys = &KeysResource{c: c}
	c.Labels = &LabelsResource{c: c}
	c.LandingPages = &LandingPagesResource{c: c}
	c.Marketplace = &MarketplaceResource{c: c}
	c.Monetization = &MonetizationResource{c: c}
	c.Notifications = &NotificationsResource{c: c}
	c.Preferences = &PreferencesResource{c: c}
	c.Referrals = &ReferralsResource{c: c}
	c.Sandbox = &SandboxResource{c: c}
	c.Segments = &SegmentsResource{c: c}
	c.Settings = &SettingsResource{c: c}
	c.Templates = &TemplatesResource{c: c}
	c.Track = &TrackResource{c: c}
	c.Validate = &ValidateResource{c: c}
	c.Wallet = &WalletResource{c: c}
	c.Warmup = &WarmupResource{c: c}
	c.Workspaces = &WorkspacesResource{c: c}
}
