// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type InboxResource struct{ c *Client }

// AiImprove — POST /inbox/ai/improve
func (r *InboxResource) AiImprove(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/ai/improve"+encodeQuery(params), body)
}

// AiReply — POST /inbox/ai/reply
func (r *InboxResource) AiReply(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/ai/reply"+encodeQuery(params), body)
}

// AiSummarize — POST /inbox/ai/summarize
func (r *InboxResource) AiSummarize(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/ai/summarize"+encodeQuery(params), body)
}

// Categorize — POST /inbox/categorize
func (r *InboxResource) Categorize(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/categorize"+encodeQuery(params), body)
}

// Conversations — GET /inbox/conversations
func (r *InboxResource) Conversations(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/inbox/conversations"+encodeQuery(params), nil)
}

// ConversationsMessages — GET /inbox/conversations/:id/messages
func (r *InboxResource) ConversationsMessages(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/inbox/conversations/%s/messages", url.PathEscape(id))+encodeQuery(params), nil)
}

// ConversationsSend — POST /inbox/conversations/:id/send
func (r *InboxResource) ConversationsSend(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/inbox/conversations/%s/send", url.PathEscape(id))+encodeQuery(params), body)
}

// CreateSnooze — POST /inbox/snooze
func (r *InboxResource) CreateSnooze(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/snooze"+encodeQuery(params), body)
}

// DeleteSnooze — DELETE /inbox/snooze
func (r *InboxResource) DeleteSnooze(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", "/inbox/snooze"+encodeQuery(params), body)
}

// ListSnooze — GET /inbox/snooze
func (r *InboxResource) ListSnooze(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/inbox/snooze"+encodeQuery(params), nil)
}

// Unsubscribe — POST /inbox/unsubscribe
func (r *InboxResource) Unsubscribe(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/inbox/unsubscribe"+encodeQuery(params), body)
}
