// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type TemplatesResource struct{ c *Client }

// Create — POST /v1/templates
func (r *TemplatesResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/templates"+encodeQuery(params), body)
}

// List — GET /v1/templates
func (r *TemplatesResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/templates"+encodeQuery(params), nil)
}

// Render — POST /v1/templates/render
func (r *TemplatesResource) Render(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/templates/render"+encodeQuery(params), body)
}
