// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type FormsResource struct{ c *Client }

// Create — POST /forms
func (r *FormsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/forms"+encodeQuery(params), body)
}

// Delete — DELETE /forms/:id
func (r *FormsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", fmt.Sprintf("/forms/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// Embed — GET /forms/:id/embed
func (r *FormsResource) Embed(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/forms/%s/embed", url.PathEscape(id))+encodeQuery(params), nil)
}

// Get — GET /forms/:id
func (r *FormsResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/forms/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /forms
func (r *FormsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/forms"+encodeQuery(params), nil)
}

// Submissions — GET /forms/:id/submissions
func (r *FormsResource) Submissions(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/forms/%s/submissions", url.PathEscape(id))+encodeQuery(params), nil)
}

// Submit — POST /public/forms/:id/submit — public form submission (no API key required)
func (r *FormsResource) Submit(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/public/forms/%s/submit", url.PathEscape(id))+encodeQuery(params), body)
}

// Update — PATCH /forms/:id
func (r *FormsResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/forms/%s", url.PathEscape(id))+encodeQuery(params), body)
}
