// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type EmailResource struct{ c *Client }

// Get — GET /v1/emails/:id
func (r *EmailResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/v1/emails/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /v1/emails
func (r *EmailResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/emails"+encodeQuery(params), nil)
}

// Send — POST /v1/send
func (r *EmailResource) Send(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/send"+encodeQuery(params), body)
}

// Update — PATCH /v1/emails/:id
func (r *EmailResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/v1/emails/%s", url.PathEscape(id))+encodeQuery(params), body)
}
