// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type ReferralsResource struct{ c *Client }

// Claim — POST /referrals/claim
func (r *ReferralsResource) Claim(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/referrals/claim"+encodeQuery(params), body)
}

// Generate — POST /referrals/generate
func (r *ReferralsResource) Generate(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/referrals/generate"+encodeQuery(params), body)
}

// Leaderboard — GET /referrals/leaderboard
func (r *ReferralsResource) Leaderboard(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/referrals/leaderboard"+encodeQuery(params), nil)
}

// List — GET /referrals
func (r *ReferralsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/referrals"+encodeQuery(params), nil)
}

// LogShare — POST /referrals/log-share
func (r *ReferralsResource) LogShare(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/referrals/log-share"+encodeQuery(params), body)
}

// MilestoneClaims — GET /referrals/milestone-claims
func (r *ReferralsResource) MilestoneClaims(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/referrals/milestone-claims"+encodeQuery(params), nil)
}

// Milestones — GET /referrals/milestones
func (r *ReferralsResource) Milestones(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/referrals/milestones"+encodeQuery(params), nil)
}

// Nudge — GET /referrals/nudge
func (r *ReferralsResource) Nudge(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/referrals/nudge"+encodeQuery(params), nil)
}
