// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type DomainsResource struct{ c *Client }

// Create — POST /domains
func (r *DomainsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/domains"+encodeQuery(params), body)
}

// Delete — DELETE /domains
func (r *DomainsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/domains"+encodeQuery(query), nil)
}

// List — GET /domains
func (r *DomainsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/domains"+encodeQuery(params), nil)
}

// Verify — POST /domains/:id/verify
func (r *DomainsResource) Verify(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/domains/%s/verify", url.PathEscape(id))+encodeQuery(params), nil)
}
