// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type AnalyticsResource struct{ c *Client }

// List — GET /v1/analytics
func (r *AnalyticsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/analytics"+encodeQuery(params), nil)
}

// RevenueAttribution — GET /v1/revenue/attribution
func (r *AnalyticsResource) RevenueAttribution(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/revenue/attribution"+encodeQuery(params), nil)
}
