// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type MarketplaceResource struct{ c *Client }

// Create — POST /marketplace
func (r *MarketplaceResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/marketplace"+encodeQuery(params), body)
}

// CreatePremium — POST /marketplace/premium
func (r *MarketplaceResource) CreatePremium(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/marketplace/premium"+encodeQuery(params), body)
}

// CreateReview — POST /marketplace/:slug/review
func (r *MarketplaceResource) CreateReview(ctx context.Context, slug string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/marketplace/%s/review", url.PathEscape(slug))+encodeQuery(params), body)
}

// CreateSubmit — POST /marketplace/submit
func (r *MarketplaceResource) CreateSubmit(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/marketplace/submit"+encodeQuery(params), body)
}

// Download — POST /marketplace/:slug/download
func (r *MarketplaceResource) Download(ctx context.Context, slug string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/marketplace/%s/download", url.PathEscape(slug))+encodeQuery(params), nil)
}

// Get — GET /marketplace/:slug — public catalogue detail (no API key required)
func (r *MarketplaceResource) Get(ctx context.Context, slug string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/marketplace/%s", url.PathEscape(slug))+encodeQuery(params), nil)
}

// GetReview — GET /marketplace/:slug/review
func (r *MarketplaceResource) GetReview(ctx context.Context, slug string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/marketplace/%s/review", url.PathEscape(slug))+encodeQuery(params), nil)
}

// List — GET /marketplace
func (r *MarketplaceResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/marketplace"+encodeQuery(params), nil)
}

// ListMy — GET /marketplace/my
func (r *MarketplaceResource) ListMy(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/marketplace/my"+encodeQuery(params), nil)
}

// ListPremium — GET /marketplace/premium
func (r *MarketplaceResource) ListPremium(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/marketplace/premium"+encodeQuery(params), nil)
}

// ListSubmit — GET /marketplace/submit
func (r *MarketplaceResource) ListSubmit(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/marketplace/submit"+encodeQuery(params), nil)
}

// Purchase — POST /marketplace/:slug/purchase
func (r *MarketplaceResource) Purchase(ctx context.Context, slug string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/marketplace/%s/purchase", url.PathEscape(slug))+encodeQuery(params), nil)
}

// UpdateMy — PATCH /marketplace/my
func (r *MarketplaceResource) UpdateMy(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", "/marketplace/my"+encodeQuery(params), body)
}
