// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type DraftsResource struct{ c *Client }

// Create — POST /drafts
func (r *DraftsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/drafts"+encodeQuery(params), body)
}

// Delete — DELETE /drafts
func (r *DraftsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/drafts"+encodeQuery(query), nil)
}

// List — GET /drafts
func (r *DraftsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/drafts"+encodeQuery(params), nil)
}

// Update — PUT /drafts
func (r *DraftsResource) Update(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PUT", "/drafts"+encodeQuery(params), body)
}
