// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type TrackResource struct{ c *Client }

// Event — POST /v1/track/event
func (r *TrackResource) Event(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/track/event"+encodeQuery(params), body)
}

// Purchase — POST /v1/track/purchase
func (r *TrackResource) Purchase(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/track/purchase"+encodeQuery(params), body)
}
