// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type LandingPagesResource struct{ c *Client }

// Create — POST /v1/landing-pages
func (r *LandingPagesResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/landing-pages"+encodeQuery(params), body)
}

// Delete — DELETE /landing-pages/:id
func (r *LandingPagesResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", fmt.Sprintf("/landing-pages/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// Get — GET /landing-pages/:id
func (r *LandingPagesResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/landing-pages/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /landing-pages
func (r *LandingPagesResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/landing-pages"+encodeQuery(params), nil)
}

// Update — PATCH /landing-pages/:id
func (r *LandingPagesResource) Update(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/landing-pages/%s", url.PathEscape(id))+encodeQuery(params), body)
}
