// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type PreferencesResource struct{ c *Client }

// List — GET /preferences — signed preference-centre token rather than an API key (no API key required)
func (r *PreferencesResource) List(ctx context.Context, token string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("token") == "" {
		query.Set("token", token)
	}
	return r.c.Do(ctx, "GET", "/preferences"+encodeQuery(query), nil)
}

// Update — PUT /preferences — signed preference-centre token rather than an API key (no API key required)
func (r *PreferencesResource) Update(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PUT", "/preferences"+encodeQuery(params), body)
}
