// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type IntegrationsResource struct{ c *Client }

// Get — GET /integrations/:id
func (r *IntegrationsResource) Get(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", fmt.Sprintf("/integrations/%s", url.PathEscape(id))+encodeQuery(params), nil)
}

// List — GET /integrations
func (r *IntegrationsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/integrations"+encodeQuery(params), nil)
}

// Toggle — PATCH /integrations/:id/toggle
func (r *IntegrationsResource) Toggle(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", fmt.Sprintf("/integrations/%s/toggle", url.PathEscape(id))+encodeQuery(params), body)
}

// ZapierAction — POST /integrations/zapier/action
func (r *IntegrationsResource) ZapierAction(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/integrations/zapier/action"+encodeQuery(params), body)
}

// ZapierTrigger — GET /integrations/zapier/trigger
func (r *IntegrationsResource) ZapierTrigger(ctx context.Context, event string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("event") == "" {
		query.Set("event", event)
	}
	return r.c.Do(ctx, "GET", "/integrations/zapier/trigger"+encodeQuery(query), nil)
}
