// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type WalletResource struct{ c *Client }

// Credit — POST /v1/wallet/credit
func (r *WalletResource) Credit(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/wallet/credit"+encodeQuery(params), body)
}

// Debit — POST /v1/wallet/debit
func (r *WalletResource) Debit(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/wallet/debit"+encodeQuery(params), body)
}

// List — GET /v1/wallet
func (r *WalletResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/wallet"+encodeQuery(params), nil)
}
