// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type SandboxResource struct{ c *Client }

// Delete — DELETE /v1/sandbox
func (r *SandboxResource) Delete(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", "/v1/sandbox"+encodeQuery(params), nil)
}

// List — GET /v1/sandbox
func (r *SandboxResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/sandbox"+encodeQuery(params), nil)
}
