// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type BillingResource struct{ c *Client }

// CreateSubscription — POST /v1/subscription
func (r *BillingResource) CreateSubscription(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/subscription"+encodeQuery(params), body)
}

// CreditRates — GET /v1/credit-rates
func (r *BillingResource) CreditRates(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/credit-rates"+encodeQuery(params), nil)
}

// DeleteSubscription — DELETE /v1/subscription
func (r *BillingResource) DeleteSubscription(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "DELETE", "/v1/subscription"+encodeQuery(params), body)
}

// ListSubscription — GET /v1/subscription
func (r *BillingResource) ListSubscription(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/subscription"+encodeQuery(params), nil)
}

// Plan — GET /v1/plan
func (r *BillingResource) Plan(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/plan"+encodeQuery(params), nil)
}

// PlanLimits — GET /v1/plan-limits
func (r *BillingResource) PlanLimits(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/plan-limits"+encodeQuery(params), nil)
}
