// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"net/url"
)

type ContactsResource struct{ c *Client }

// Create — POST /v1/contacts
func (r *ContactsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/contacts"+encodeQuery(params), body)
}

// Delete — DELETE /v1/contacts
func (r *ContactsResource) Delete(ctx context.Context, id string, params url.Values) (map[string]any, error) {
	query := cloneValues(params)
	if query.Get("id") == "" {
		query.Set("id", id)
	}
	return r.c.Do(ctx, "DELETE", "/v1/contacts"+encodeQuery(query), nil)
}

// Import — POST /v1/contacts/import
func (r *ContactsResource) Import(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/contacts/import"+encodeQuery(params), body)
}

// List — GET /v1/contacts
func (r *ContactsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/contacts"+encodeQuery(params), nil)
}

// Update — PATCH /v1/contacts
func (r *ContactsResource) Update(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "PATCH", "/v1/contacts"+encodeQuery(params), body)
}
