// AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
// Do not edit by hand — changes are overwritten. To change this surface,
// change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
// the generator.

package misarmail

import (
	"context"
	"fmt"
	"net/url"
)

type AbTestsResource struct{ c *Client }

// Create — POST /v1/ab-tests
func (r *AbTestsResource) Create(ctx context.Context, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", "/v1/ab-tests"+encodeQuery(params), body)
}

// List — GET /v1/ab-tests
func (r *AbTestsResource) List(ctx context.Context, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "GET", "/v1/ab-tests"+encodeQuery(params), nil)
}

// Winner — POST /v1/ab-tests/:id/winner
func (r *AbTestsResource) Winner(ctx context.Context, id string, body any, params url.Values) (map[string]any, error) {
	return r.c.Do(ctx, "POST", fmt.Sprintf("/v1/ab-tests/%s/winner", url.PathEscape(id))+encodeQuery(params), body)
}
