# frozen_string_literal: true

# AUTO-GENERATED by scripts/generate-sdks.mjs from sdks/manifest.json.
# Do not edit by hand — changes are overwritten. To change this surface,
# change the API route, re-run scripts/sync-sdk-manifest.mjs, then re-run
# the generator.

require_relative "generated/ab_tests"
require_relative "generated/ai"
require_relative "generated/analytics"
require_relative "generated/automations"
require_relative "generated/billing"
require_relative "generated/campaigns"
require_relative "generated/compliance"
require_relative "generated/contacts"
require_relative "generated/dedicated_ips"
require_relative "generated/deliverability"
require_relative "generated/dmarc"
require_relative "generated/domains"
require_relative "generated/drafts"
require_relative "generated/email"
require_relative "generated/email_accounts"
require_relative "generated/forms"
require_relative "generated/inbound"
require_relative "generated/inbox"
require_relative "generated/integrations"
require_relative "generated/keys"
require_relative "generated/labels"
require_relative "generated/landing_pages"
require_relative "generated/marketplace"
require_relative "generated/monetization"
require_relative "generated/notifications"
require_relative "generated/preferences"
require_relative "generated/referrals"
require_relative "generated/sandbox"
require_relative "generated/segments"
require_relative "generated/settings"
require_relative "generated/templates"
require_relative "generated/track"
require_relative "generated/validate"
require_relative "generated/wallet"
require_relative "generated/warmup"
require_relative "generated/workspaces"

module MisarMail
  module Generated
    # Every generated resource, attached to a client in one place.
    class Resources
      attr_reader :ab_tests
      attr_reader :ai
      attr_reader :analytics
      attr_reader :automations
      attr_reader :billing
      attr_reader :campaigns
      attr_reader :compliance
      attr_reader :contacts
      attr_reader :dedicated_ips
      attr_reader :deliverability
      attr_reader :dmarc
      attr_reader :domains
      attr_reader :drafts
      attr_reader :email
      attr_reader :email_accounts
      attr_reader :forms
      attr_reader :inbound
      attr_reader :inbox
      attr_reader :integrations
      attr_reader :keys
      attr_reader :labels
      attr_reader :landing_pages
      attr_reader :marketplace
      attr_reader :monetization
      attr_reader :notifications
      attr_reader :preferences
      attr_reader :referrals
      attr_reader :sandbox
      attr_reader :segments
      attr_reader :settings
      attr_reader :templates
      attr_reader :track
      attr_reader :validate
      attr_reader :wallet
      attr_reader :warmup
      attr_reader :workspaces

      def initialize(core)
        @ab_tests = AbTestsResource.new(core)
        @ai = AiResource.new(core)
        @analytics = AnalyticsResource.new(core)
        @automations = AutomationsResource.new(core)
        @billing = BillingResource.new(core)
        @campaigns = CampaignsResource.new(core)
        @compliance = ComplianceResource.new(core)
        @contacts = ContactsResource.new(core)
        @dedicated_ips = DedicatedIpsResource.new(core)
        @deliverability = DeliverabilityResource.new(core)
        @dmarc = DmarcResource.new(core)
        @domains = DomainsResource.new(core)
        @drafts = DraftsResource.new(core)
        @email = EmailResource.new(core)
        @email_accounts = EmailAccountsResource.new(core)
        @forms = FormsResource.new(core)
        @inbound = InboundResource.new(core)
        @inbox = InboxResource.new(core)
        @integrations = IntegrationsResource.new(core)
        @keys = KeysResource.new(core)
        @labels = LabelsResource.new(core)
        @landing_pages = LandingPagesResource.new(core)
        @marketplace = MarketplaceResource.new(core)
        @monetization = MonetizationResource.new(core)
        @notifications = NotificationsResource.new(core)
        @preferences = PreferencesResource.new(core)
        @referrals = ReferralsResource.new(core)
        @sandbox = SandboxResource.new(core)
        @segments = SegmentsResource.new(core)
        @settings = SettingsResource.new(core)
        @templates = TemplatesResource.new(core)
        @track = TrackResource.new(core)
        @validate = ValidateResource.new(core)
        @wallet = WalletResource.new(core)
        @warmup = WarmupResource.new(core)
        @workspaces = WorkspacesResource.new(core)
      end
    end
  end
end
