name: Publish Flutter SDK
on:
  push:
    tags: ['flutter/v*']
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - run: flutter pub get
        working-directory: flutter
      - run: flutter analyze
        working-directory: flutter
      - run: flutter test
        working-directory: flutter
      - run: dart pub publish --force
        working-directory: flutter
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
